os: osx
language: node_js
osx_image: xcode9.2
cache:
    directories:
          - $HOME/Library/Caches/Homebrew
before_install:
  - brew update
install:
  - brew install ansible
after_success:
  - "echo Done!"
