os: osx
language: generic
osx_image: xcode9.2
cache:
    directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/.cache/pip
script: ./start.sh
notifications:
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_start: always