os: osx
language: generic
osx_image: xcode10.1
cache:
    directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/.cache/pip
script: ./start.sh
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
